# Generated by Django 5.1.1 on 2024-10-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag_type',
            field=models.CharField(choices=[('carousel', 'Carousel'), ('product', 'Product')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
